# src/license_manager.py
#
# This module generates and verifies software license files.
#
# A license is a JSON document that records:
#   - The date it was created.
#   - The expiry date (optional).
#   - The machine ID it is locked to (optional).
#   - An HMAC-SHA256 signature that proves the file has not been tampered with.
#
# The machine ID is a SHA-256 hash of hardware identifiers collected by psutil:
# the MAC address, CPU count, and disk serial information.  Hashing means we
# never store raw hardware identifiers in the license file.
#
# The HMAC secret key is now a caller-supplied parameter on every signing and
# verification call.  The caller is responsible for loading the secret via
# src.build_secret.load_or_create_secret().  This change means:
#   - Each build has its own secret, generated by "pyshield build".
#   - The secret is never stored in the source code.
#   - An attacker who extracts the key from one binary cannot forge licenses
#     for any other customer's binary.
#
# The old hard-coded constant is preserved below as a comment marked DEPRECATED
# so that anyone reading the git history understands what changed and why.

import datetime   # Used to compute expiry dates and check them at verification.
import hashlib    # Provides SHA-256 and HMAC for hashing and signing.
import hmac       # Provides the HMAC signing function.
import json       # Licenses are stored as JSON text files.
import os         # Used to resolve file paths.
import uuid       # Used to read the hardware MAC address.

import psutil     # Used to read CPU and disk information for the machine ID.

# DEPRECATED: The hard-coded HMAC key that was used in all PyShield versions
# before per-build secrets were introduced.  This constant is no longer used
# anywhere in the codebase.  It is kept here only so git history is readable.
# Do NOT use this value in new code.  Use src.build_secret.load_or_create_secret()
# to obtain the HMAC secret.
#
# _LICENSE_HMAC_KEY = b"pyshield-license-key"  # noqa: ERA001 (intentionally dead)


def get_machine_id() -> str:
    """Compute a stable machine identifier from hardware characteristics.

    Reads the MAC address of the first network interface, the number of CPU
    cores, and the total size of the first physical disk.  Concatenates these
    values and returns their SHA-256 hex digest.

    The result is stable across reboots on the same hardware.  It changes if
    the user replaces a network card, adds or removes CPU cores (rare), or
    replaces the primary disk.

    Returns
    -------
    str
        A 64-character hexadecimal SHA-256 digest that uniquely identifies
        this machine.
    """

    # Get the MAC address as a 48-bit integer, then convert to a string.
    # uuid.getnode() reads the MAC address from the operating system.
    mac_address = str(uuid.getnode())

    # Get the number of logical CPU cores as a string.
    # psutil.cpu_count() returns an integer like 8 or 16.
    cpu_count = str(psutil.cpu_count(logical=True))

    # Get the total size of the first disk partition in bytes as a string.
    # psutil.disk_partitions() returns a list of mounted partitions.
    # We use the first partition as a stable reference point.
    try:
        # Get the list of disk partitions.
        partitions = psutil.disk_partitions()

        # Take the mountpoint of the first partition.
        first_mountpoint = partitions[0].mountpoint if partitions else "unknown"

        # Get disk usage statistics for that mountpoint.
        disk_usage = psutil.disk_usage(first_mountpoint)

        # Use the total disk size as part of the identity string.
        disk_total = str(disk_usage.total)

    except Exception:
        # If disk information cannot be read, use "unknown" as the placeholder.
        disk_total = "unknown"

    # Concatenate the hardware values with pipe separators.
    hardware_string = f"{mac_address}|{cpu_count}|{disk_total}"

    # Hash the hardware string with SHA-256 and return the hex digest.
    machine_id = hashlib.sha256(hardware_string.encode("utf-8")).hexdigest()

    return machine_id


def _sign_payload(payload: dict, secret: bytes) -> str:
    """Compute an HMAC-SHA256 signature for a license payload dictionary.

    The payload is serialised to a compact JSON string with sorted keys so
    that the signature is deterministic regardless of key insertion order.

    Parameters
    ----------
    payload : dict
        The license data dictionary (without the "signature" key).
    secret : bytes
        The HMAC secret key to sign with.  This must be the same secret that
        was embedded in the protected binary so that the binary's verify step
        can reproduce the signature.  Obtain it via
        src.build_secret.load_or_create_secret().

    Returns
    -------
    str
        The hexadecimal HMAC-SHA256 digest.
    """

    # Serialise the payload to a compact JSON string with sorted keys.
    # sort_keys=True ensures the same dictionary always produces the same string,
    # regardless of the order keys were inserted into the dict.
    payload_bytes = json.dumps(payload, sort_keys=True).encode("utf-8")

    # Compute the HMAC using SHA-256 and the caller-supplied secret key.
    # Using the caller-supplied key (instead of a module-level constant) means
    # each build can have its own key, limiting the blast radius of any single
    # key compromise.
    signature = hmac.new(secret, payload_bytes, hashlib.sha256)

    # Return the hex digest as a string.
    return signature.hexdigest()


def generate_license(
    output_path: str,
    machine_lock: bool = False,
    days: int = 0,
    secret: bytes = None,
) -> str:
    """Generate a signed license file and write it to disk.

    Parameters
    ----------
    output_path : str
        Path where the license file will be written.
    machine_lock : bool, optional
        If True, record the current machine's hardware ID in the license so
        that it will only validate on this machine.  Defaults to False.
    days : int, optional
        Number of days from today until the license expires.  If 0 or
        negative, the license does not expire.  Defaults to 0.
    secret : bytes
        The HMAC secret key used to sign the license.  This must match the
        secret that was embedded in the protected binary by "pyshield build".
        Obtain it with src.build_secret.load_or_create_secret() or by reading
        the .pyshield_secret file from the build output directory.
        This parameter is required; passing None raises ValueError.

    Returns
    -------
    str
        The absolute path to the written license file.

    Raises
    ------
    ValueError
        If secret is None, because signing requires a key.
    """

    # Validate that a secret was provided.  We require the caller to supply
    # one explicitly so there is no risk of accidentally using a default or
    # shared key.  The error message tells the caller exactly how to fix this.
    if secret is None:
        raise ValueError(
            "The 'secret' parameter is required for generate_license(). "
            "Load the build secret with src.build_secret.load_or_create_secret(), "
            "or pass --secret-file on the command line."
        )

    # Resolve the output path to an absolute path.
    output_path = os.path.abspath(output_path)

    # Record today's date in ISO 8601 format (YYYY-MM-DD).
    issued_date = datetime.date.today().isoformat()

    # Build the license payload dictionary.
    # This dict will be serialised to JSON and signed.
    payload = {
        "issued": issued_date,
        "machine_id": None,   # Will be filled in below if machine_lock is True.
        "expires": None,      # Will be filled in below if days > 0.
    }

    # If machine locking is requested, compute and store the machine ID.
    if machine_lock:
        payload["machine_id"] = get_machine_id()

    # If an expiry duration was requested, compute the expiry date.
    if days and days > 0:
        # Add the requested number of days to today's date.
        expiry_date = datetime.date.today() + datetime.timedelta(days=days)

        # Store the expiry date as an ISO 8601 string.
        payload["expires"] = expiry_date.isoformat()

    # Sign the payload and add the signature to the document.
    # Pass the caller-supplied secret so the signature matches the key that
    # was embedded in the protected binary.
    payload["signature"] = _sign_payload(
        # Sign only the data fields, not the signature field itself.
        {k: v for k, v in payload.items() if k != "signature"},
        secret,
    )

    # Ensure the parent directory of the output file exists.
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    # Write the license document as indented JSON so it is human-readable
    # (and screen-reader readable) if someone opens the file in a text editor.
    with open(output_path, "w", encoding="utf-8") as license_file:
        json.dump(payload, license_file, indent=2)

    return output_path


def verify_license(license_path: str, secret: bytes = None) -> bool:
    """Verify a license file and return True if it is valid.

    Checks:
    1. The file exists and is valid JSON.
    2. The HMAC signature matches the payload (using the supplied secret).
    3. If a machine_id is present, it matches the current machine.
    4. If an expiry date is present, today's date is before the expiry.

    Parameters
    ----------
    license_path : str
        Path to the license file to verify.
    secret : bytes
        The HMAC secret key used to verify the license signature.  This must
        be the same secret that was used to sign the license (i.e., the secret
        embedded in the protected binary by "pyshield build").
        This parameter is required; passing None raises ValueError.

    Returns
    -------
    bool
        True if the license passes all checks.

    Raises
    ------
    FileNotFoundError
        If the license file does not exist.
    ValueError
        If secret is None, or if the signature check fails, the machine ID
        does not match, or the license has expired.
    """

    # Validate that a secret was provided.  The caller must supply the same
    # secret that was used to sign the license.
    if secret is None:
        raise ValueError(
            "The 'secret' parameter is required for verify_license(). "
            "Load the build secret with src.build_secret.load_or_create_secret(), "
            "provide --secret-file on the command line, or set the "
            "PYSHIELD_HMAC_KEY environment variable."
        )

    # Resolve the path to an absolute path.
    license_path = os.path.abspath(license_path)

    # Confirm the license file exists.
    if not os.path.isfile(license_path):
        raise FileNotFoundError(
            f"License file does not exist: {license_path}"
        )

    # Read and parse the JSON content of the license file.
    with open(license_path, "r", encoding="utf-8") as license_file:
        try:
            license_data = json.load(license_file)
        except json.JSONDecodeError as exc:
            raise ValueError(
                f"License file is not valid JSON: {license_path}"
            ) from exc

    # Extract the stored signature from the license document.
    stored_signature = license_data.get("signature")

    # Build the payload dict without the signature key, then re-sign it.
    payload_without_sig = {
        k: v for k, v in license_data.items() if k != "signature"
    }
    # Pass the caller-supplied secret so we use the same key that was used
    # to sign the license originally.
    expected_signature = _sign_payload(payload_without_sig, secret)

    # Compare the stored signature with the freshly computed one.
    # hmac.compare_digest is used instead of "==" to prevent timing attacks.
    if not hmac.compare_digest(str(stored_signature), expected_signature):
        raise ValueError(
            "License signature is invalid. The license file may have been tampered with."
        )

    # If the license records a machine ID, verify it matches this machine.
    stored_machine_id = license_data.get("machine_id")
    if stored_machine_id is not None:
        current_machine_id = get_machine_id()
        if stored_machine_id != current_machine_id:
            raise ValueError(
                "License is locked to a different machine and cannot be used here."
            )

    # If the license records an expiry date, verify it has not passed.
    expires_str = license_data.get("expires")
    if expires_str is not None:
        # Parse the ISO 8601 expiry date string into a date object.
        try:
            expiry_date = datetime.date.fromisoformat(expires_str)
        except ValueError as exc:
            raise ValueError(
                f"License contains an invalid expiry date format: {expires_str}"
            ) from exc

        # Compare the expiry date with today.
        if datetime.date.today() > expiry_date:
            raise ValueError(
                f"License expired on {expires_str}."
            )

    # All checks passed.
    return True
