# examples/demo_app/license_check.py
#
# This module provides license validation for the demo application binary.
# It is a self-contained copy of the validation logic so that the PyInstaller
# binary does not need to import from the PyShield src/ package.
#
# The license format is identical to src/license_manager.py.  However, the
# HMAC key is now a per-build secret that is embedded into the binary at
# build time.  The key is loaded in the following order:
#
#   1. From _pyshield_runtime_constants (generated by 'pyshield build' and
#      encrypted by PyArmor — this is the path used inside the built binary).
#   2. From the PYSHIELD_HMAC_KEY environment variable (64 hex chars) — this
#      is the development and CI path, used when running the unobfuscated code.
#
# If neither source is available, validation raises RuntimeError with a plain
# message explaining how to fix the configuration.
#
# Public functions:
#   validate_license(license_path) — raises ValueError if the license is bad.
#   get_machine_id()               — returns the SHA-256 machine fingerprint.
#
# All validation errors include plain-language messages that are meaningful
# when read aloud by a screen reader.

import datetime   # Used to check expiry dates against today's date.
import hashlib    # Provides SHA-256 and HMAC for hashing and signing.
import hmac       # Provides the HMAC function for constant-time comparison.
import json       # License files are stored as JSON.
import os         # Used to resolve file paths and read the env var fallback.
import uuid       # Used to read the hardware MAC address.

import psutil     # Used to read CPU count and disk size for machine fingerprinting.

# ---------------------------------------------------------------------------
# Load the per-build HMAC secret.
# ---------------------------------------------------------------------------
# When running as a built, PyArmor-obfuscated binary, _pyshield_runtime_constants
# is an encrypted module embedded inside the binary.  Importing it gives us the
# HMAC_KEY that was generated during 'pyshield build'.
#
# When running the unobfuscated source (development, testing, CI that does not
# go through a full build), the module will not exist.  In that case we fall
# back to the PYSHIELD_HMAC_KEY environment variable so developers and CI
# pipelines can still run the code with a known test key.
try:
    # This import succeeds inside the built binary (where PyArmor has encrypted
    # the constants file and included it in the bundle).
    from _pyshield_runtime_constants import HMAC_KEY as _LICENSE_HMAC_KEY  # type: ignore[import-not-found]
except ImportError:
    # We are running in development mode (or a test environment) where the
    # obfuscated constants module is not present.  Read the key from the
    # environment variable instead.
    _env_key = os.environ.get("PYSHIELD_HMAC_KEY")
    if _env_key:
        # Decode the 64-character hex string to 32 bytes.
        try:
            _LICENSE_HMAC_KEY = bytes.fromhex(_env_key)
        except ValueError as _exc:
            raise RuntimeError(
                "PYSHIELD_HMAC_KEY environment variable is set but is not a valid "
                "64-character hex string.  "
                "Generate a valid value with: "
                "python -c \"import secrets; print(secrets.token_bytes(32).hex())\""
            ) from _exc
    else:
        # Neither the obfuscated module nor the env var is available.
        # Raise a clear error so the developer knows exactly what to do.
        raise RuntimeError(
            "HMAC key not available for license validation.  "
            "For development, set the PYSHIELD_HMAC_KEY environment variable "
            "to the 64-character hex string from your build's .pyshield_secret file.  "
            "For a production binary, run 'pyshield build' to embed the key."
        )


def get_machine_id() -> str:
    """Compute a stable hardware fingerprint for the current machine.

    Reads the MAC address, CPU count, and first disk size.  Concatenates
    them and returns the SHA-256 hex digest.  This value is stable across
    reboots on the same hardware.

    Returns:
        A 64-character hexadecimal string that uniquely identifies this machine.
    """

    # Read the MAC address as a large integer, then convert to a string.
    mac_address = str(uuid.getnode())

    # Read the number of logical CPU cores.
    cpu_count = str(psutil.cpu_count(logical=True))

    # Read the total size of the first disk partition as a tie-breaker.
    try:
        partitions = psutil.disk_partitions()
        first_mountpoint = partitions[0].mountpoint if partitions else "unknown"
        disk_usage = psutil.disk_usage(first_mountpoint)
        disk_total = str(disk_usage.total)
    except Exception:
        # If disk info is unavailable, use a placeholder.
        disk_total = "unknown"

    # Combine the hardware values and hash them.
    hardware_string = f"{mac_address}|{cpu_count}|{disk_total}"
    return hashlib.sha256(hardware_string.encode("utf-8")).hexdigest()


def _sign_payload(payload: dict) -> str:
    """Compute the HMAC-SHA256 signature for a license payload.

    Args:
        payload: The license data dictionary without the "signature" key.

    Returns:
        The hexadecimal HMAC-SHA256 digest string.
    """

    # Serialise with sorted keys so the signature is deterministic.
    payload_bytes = json.dumps(payload, sort_keys=True).encode("utf-8")
    signature = hmac.new(_LICENSE_HMAC_KEY, payload_bytes, hashlib.sha256)
    return signature.hexdigest()


def validate_license(license_path: str) -> None:
    """Validate a PyShield license file.

    Checks the HMAC signature, machine-lock binding, and expiry date.
    Raises ValueError with a descriptive message if any check fails.

    Args:
        license_path: Path to the .lic JSON license file.

    Raises:
        FileNotFoundError: If the license file does not exist.
        ValueError: If the signature is wrong, the machine does not match,
                    or the license has expired.  The error message explains
                    which check failed in plain English.
    """

    # Resolve the path to an absolute form for cleaner error messages.
    license_path = os.path.abspath(license_path)

    # Confirm the license file exists.
    if not os.path.isfile(license_path):
        raise FileNotFoundError(
            f"License file not found: {license_path}. "
            "Please generate a license using: python pyshield.py license generate"
        )

    # Read and parse the JSON content.
    with open(license_path, "r", encoding="utf-8") as license_file:
        try:
            license_data = json.load(license_file)
        except json.JSONDecodeError as exc:
            raise ValueError(
                f"License file contains invalid JSON: {license_path}"
            ) from exc

    # Extract the stored signature.
    stored_signature = license_data.get("signature")

    # Recompute the signature from the data fields and compare.
    payload_without_sig = {
        k: v for k, v in license_data.items() if k != "signature"
    }
    expected_signature = _sign_payload(payload_without_sig)

    # Use hmac.compare_digest to prevent timing-attack guessing.
    if not hmac.compare_digest(str(stored_signature), expected_signature):
        raise ValueError(
            "License signature is invalid. "
            "The license file may have been tampered with or was not issued by PyShield."
        )

    # If the license is machine-locked, verify this is the correct machine.
    stored_machine_id = license_data.get("machine_id")
    if stored_machine_id is not None:
        current_machine_id = get_machine_id()
        if stored_machine_id != current_machine_id:
            raise ValueError(
                f"License is locked to a different machine and cannot be used here. "
                f"This machine ID is: {current_machine_id}. "
                "Contact support with your machine ID to obtain the correct license."
            )

    # If the license has an expiry date, verify it has not passed.
    expires_str = license_data.get("expires")
    if expires_str is not None:
        try:
            expiry_date = datetime.date.fromisoformat(expires_str)
        except ValueError as exc:
            raise ValueError(
                f"License contains an unreadable expiry date: {expires_str}"
            ) from exc

        # Compare today's date with the expiry date.
        if datetime.date.today() > expiry_date:
            raise ValueError(
                f"License expired on {expires_str}. "
                "Please contact support to renew your license."
            )

    # All checks passed.  The license is valid.
